project:
  type: website
  output-dir: docs

website:
  title: "Carl Klein"
  favicon: images/MountRainier.jpg
  page-footer:
    center: |
      <span class="container"><strong>[Contact Carl Klein](mailto:carlj.klein@gmail.com){target="_blank"}</strong></span>
    background: "#2C3E50"
      
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Featured Projects"
        href: featured_projects.qmd
      - text: "All Projects"
        href: projects.qmd
      - text: "Virtual Resume"
        href: virtual-resume.qmd
      - text: "Downloadable Resume"
        href: resume.qmd
        
    right:
      - icon: github
        menu:
          - text: "Carl Klein's Main Page"
            href: https://github.com/clickityKlein
          - text: "Carl Klein's Repositories"
            href: https://github.com/clickityKlein?tab=repositories
          - text: "Source Code (this website)"
            href: https://github.com/clickityKlein/Carl-Klein
      - icon: linkedin
        href: https://www.linkedin.com/in/carl-klein/
      - icon: envelope
        href: mailto:carlj.klein@gmail.com

format:
  html:
    email-obfuscation: javascript
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    theme: flatly
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#2C3E50"
    toc: true
    


