---
title: "VBA Projects"
author: "Carl Klein"
date: "2022-04-24"
categories: [excel, vba, automation, widgets]
---

My initial data science projects were small scale VBA based automation projects.

While I was a Benefits Data Analyst, the majority of my team's work was in Excel, so I created tools using VBA to automate several processes. Additionally, these were added to my portfolio prior to a fuller understanding of Git and writing "proper" READMEs.

*These models were built in a generalized scope prior to implementing at my workplace.*

<a href="https://github.com/clickityKlein/VBA-Large-Claim-Automation">GitHub Repository - Large Claimant Automation Tool</a>

<a href="https://github.com/clickityKlein/VBA-Master-Database">GitHub Repository - Master Database Tool</a>


These were truly the projects that started me down the road to data science, so I believe they are a staple of my portfolio. I was attempting to implement and automate both simple and complex tasks for an analyst team, but had the limitation of staying within Excel. Naturally, I taught myself VBA and begin to program solutions for my team. I was very proud of these! 
